apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecosia-webapp-ingress
  namespace: ecosia-webapp
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: local.ecosia.org
      http:
        paths:
          - path: /tree
            pathType: Prefix
            backend:
              service:
                name: ecosia-webapp
                port:
                  name: custom-port